### ISSUE TITLE
新建接口，导入Swagger文件功能支持无type字段定义的object类型

### ISSUE THREAD

**Issue by yuanfux** [x-orpheus/nei-toolkit#115]
支持例如以下的`yaml`文件定义
```yml
ItemQcBasicInfo:
    required:
    - addedTime
    - itemId
    - itemName
    - phyCategory1Name
    - qcCategory1Name
    - sqe
    - sqeGroup
    - supplierId
    properties:
      itemName:
        type: string
        description: 商品名称
      itemId:
        type: string
        description: 商品ID
      supplierId:
        type: string
        description: 供应商ID
      sqe:
        type: string
        description: SQE
      sqeGroup:
        type: string
        description: SQE组
      phyCategory1Name:
        type: string
        description: 物理一级类目
      qcCategory1Name:
        type: string
        description: 品控一级类目
      addedTime:
        type: integer
        format: int64
        description: 上架时间
```
